def list_operations():
    my_list = [1, 5, 2, 3, 4]
    print("Starting list:", my_list)
    my_list.append(6)
    print("List after appending:", my_list)
    my_list.extend([7, 8, 9])
    print("List after extending:", my_list)
    my_list.insert(2, 10)
    print("List after inserting:", my_list)
    my_list.remove(5)
    print("List after removing:", my_list)
    my_list.sort()
    print("List after sorting:", my_list)
    my_list.reverse()
    print("List after reversing:", my_list)
    my_list_copy = my_list.copy()
    print("Copy of the list:", my_list_copy)
    my_list.clear()
    print("List cleared:", my_list)
list_operations()
